package com.example.n7_tiker_lock.gui;

import com.example.n7_tiker_lock.model.Tiker;
import com.example.n7_tiker_lock.services.TikerService;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class Principal extends JFrame {
    public JPanel panel;
    public JPanel panel_con_botones;
    public JTextArea textAreaLogs;
    private JButton btnReload;
    private JPanel panel_logs;
    private JScrollPane scrollLogs;


    private final TikerService tikerServ;

    public Principal(TikerService tikerServ) {
        setContentPane(panel);
        setTitle("N7 Tiker Lock");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.tikerServ = tikerServ;

        listarBotones();
        btnReload.addActionListener(e -> {
            log("🔄 Recargando lista...");
            listarBotones();
        });
    }

    public void listarBotones() {
        List<Tiker> tikers = new ArrayList<>();
        try {
            panel_con_botones.removeAll(); // limpiar antes de recargar
            tikers = tikerServ.getTikers();

            log("Cargando botones...");
        } catch (Exception exception) {
            tikers = new ArrayList<>();
            log("Tiro una Exepcion al intentar buscar tikers");
            log(exception.getMessage());
        }


        if (!tikers.isEmpty()) {
            for (Tiker tiker : tikers) {
                JButton boton = new JButton(tiker.getSymbol());

                // quitar barras '/' en el simbolo
                String symbol = tiker.getSymbol();
                int slashIndex = symbol.indexOf("/");

                if (slashIndex != -1) {
                    boton.setText(symbol.substring(0, slashIndex));
                } else {
                    boton.setText(symbol);
                }
                // fin quitar barras

                // configs para BOTON, quitar contorno, focus, etc.
                boton.setFocusPainted(false);
                boton.setFocusable(false);
                boton.setBorderPainted(false);

                // Seter colores primeramente a la hora de cargar tikers, antes de interactuarlos
                if (tiker.getActive() == 0) {
                    boton.setBackground(new Color(186, 186, 186));
                } else {
                    boton.setBackground(new Color(132, 208, 55));
                }

                boton.addActionListener(e -> {
                    try {
                        log("Presionaste: " + tiker.getSymbol());
                        if (tiker.getActive() == 1) {
                            boton.setBackground(new Color(186, 186, 186));
                            tiker.setActive(0);
                        } else {
                            boton.setBackground(new Color(132, 208, 55));
                            tiker.setActive(1);
                        }
                        // Comitear cambios
                        this.tikerServ.saveTiker(tiker);
                    } catch (Exception exception) {

                        log("Tiro una Exepcion al intentar cambiar estado del boton");
                        log(exception.getMessage());
                    }
                });

                panel_con_botones.add(boton);
            }

            panel_con_botones.revalidate();
            panel_con_botones.repaint();

            log("Botones cargados correctamente.");
        } else {
            log("No existen Tikers para crear botones!");
        }
    }


    //log
    public void log(String mensaje) {
        SwingUtilities.invokeLater(() -> {
            textAreaLogs.append(mensaje + "\n");
            textAreaLogs.setCaretPosition(textAreaLogs.getDocument().getLength());
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel.add(spacer2, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel.add(spacer3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        panel.add(spacer4, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        panel_con_botones = new JPanel();
        panel_con_botones.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(panel_con_botones, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnReload = new JButton();
        btnReload.setText("Reload\uD83D\uDD04");
        panel.add(btnReload, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel_logs = new JPanel();
        panel_logs.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(panel_logs, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        scrollLogs = new JScrollPane();
        panel_logs.add(scrollLogs, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        textAreaLogs = new JTextArea();
        textAreaLogs.setEditable(false);
        Font textAreaLogsFont = this.$$$getFont$$$("JetBrains Mono Light", -1, -1, textAreaLogs.getFont());
        if (textAreaLogsFont != null) textAreaLogs.setFont(textAreaLogsFont);
        textAreaLogs.setLineWrap(true);
        scrollLogs.setViewportView(textAreaLogs);
        final Spacer spacer5 = new Spacer();
        panel_logs.add(spacer5, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        panel_logs.add(spacer6, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
